// This file is generated by scripts/sync-i18n-from-sheet.js.
// Edit the Google Sheet instead of editing this file manually.
const locale = {
  "tabs": {
    "home": "Home",
    "profile": "Profile",
    "settings": "Settings"
  },
  "common": {
    "cancel": "Cancel"
  },
  "auth": {
    "logout": "Logout"
  },
  "settings": {
    "language": "Language"
  },
  "login": {
    "welcomeMessage": "Welcome, {{nickname}} ❤️"
  },
  "toast": {
    "comment": {
      "delete": "This comment has been deleted."
    }
  }
};

export default locale;
